name: Deploy to Active24 FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          protocol: sftp
          local-dir: ./
          server-dir: /milankrobot.cz/web/
          dangerous-clean-slate: false
          exclude: |
            **/.github/**
            **/.git/**
            **/node_modules/**
